[project]
name = "linearalgebra-vta"
version = "0.1.0"
description = "See README.md"
authors = [
    {name = "m.elands@student.maastrichtuniversity.nl"}
]
readme = "README.md"
requires-python = "3.13.3"
dependencies = [
    "streamlit (>=1.45.0,<2.0.0)",
    "openai (>=1.77.0,<2.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "langchain-openai (>=0.3.16,<0.4.0)",
    "fpdf (>=1.7.2,<2.0.0)",
    "langchain-chroma (>=0.2.3,<0.3.0)",
    "protobuf (==3.20.*)",
    "matplotlib (>=3.10.3,<4.0.0)",
    "google-genai (>=1.19.0,<2.0.0)",
    "pysqlite3-binary (>=0.5.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
